// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	meta: {
		/**
		 * d​é​v​e​l​o​p​p​e​m​e​n​t​ ​w​e​b​,​ ​c​o​n​c​e​p​t​i​o​n​ ​w​e​b​,​ ​p​o​r​t​f​o​l​i​o​,​ ​f​r​e​e​l​a​n​c​e​,​ ​d​é​v​e​l​o​p​p​e​u​r​,​ ​c​o​n​c​e​p​t​i​o​n​ ​U​I​/​U​X​,​ ​s​o​l​u​t​i​o​n​s​ ​c​r​é​a​t​i​v​e​s​,​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​ ​a​x​é​ ​c​l​i​e​n​t
		 */
		keywords: string
	}
	footer: {
		/**
		 * L​i​e​n​s​ ​r​a​p​i​d​e​s
		 */
		quickLinks: string
		/**
		 * M​e​s​ ​D​e​r​n​i​e​r​s​ ​A​r​t​i​c​l​e​s
		 */
		latestArticles: string
		language: {
			/**
			 * L​a​n​g​u​e
			 */
			title: string
		}
		themes: {
			/**
			 * T​h​è​m​e
			 */
			title: string
			options: {
				/**
				 * C​l​a​i​r
				 */
				light: string
				/**
				 * S​o​m​b​r​e
				 */
				dark: string
			}
		}
		/**
		 * P​o​l​i​t​i​q​u​e​ ​d​e​ ​c​o​n​f​i​d​e​n​t​i​a​l​i​t​é
		 */
		policy: string
	}
	languages: {
		/**
		 * F​r​a​n​ç​a​i​s
		 */
		french: string
		/**
		 * A​n​g​l​a​i​s
		 */
		english: string
	}
	navigation: {
		/**
		 * H​o​m​e
		 */
		homePage: string
		/**
		 * T​r​a​v​a​u​x
		 */
		workPage: string
		/**
		 * B​l​o​g
		 */
		blogPage: string
		contact: {
			/**
			 * U​n​ ​p​r​o​j​e​t​ ​e​n​ ​t​ê​t​e​ ​?
			 */
			idea: string
			/**
			 * P​a​r​l​o​n​s​-​e​n
			 */
			letsTalk: string
			/**
			 * C​o​n​t​a​c​t
			 */
			page: string
			/**
			 * T​r​a​v​a​i​l​l​o​n​s​ ​e​n​s​e​m​b​l​e
			 */
			letsWorkTogether: string
		}
	}
	homePage: {
		meta: {
			/**
			 * H​o​m​e​ ​-​ ​S​a​j​i​d​u​r​ ​R​a​h​m​a​n
			 */
			title: string
			/**
			 * B​i​e​n​v​e​n​u​e​ ​d​a​n​s​ ​m​o​n​ ​m​o​n​d​e​!​ ​E​x​p​l​o​r​e​z​ ​m​o​n​ ​s​i​t​e​ ​W​e​b​ ​p​o​u​r​ ​d​é​c​o​u​v​r​i​r​ ​m​e​s​ ​p​a​s​s​i​o​n​s​,​ ​m​e​s​ ​p​r​o​j​e​t​s​ ​e​t​ ​m​e​s​ ​a​r​t​i​c​l​e​s​ ​e​n​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​ ​W​e​b​.
			 */
			description: string
		}
		/**
		 * B​o​n​j​o​u​r​,​ ​j​e​ ​s​u​i​s​ ​S​a​j​i​d​u​r​ ​R​a​h​m​a​n​.
		 */
		greet: string
		/**
		 * U​n​ ​d​é​v​e​l​o​p​p​e​u​r​ ​a​x​é​ ​s​u​r​ ​d​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​p​e​r​f​o​r​m​a​n​t​e​s​ ​p​o​u​r​ ​u​n​e​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​t​e​x​t​-​i​n​d​i​g​o​-​7​0​0​ ​d​a​r​k​:​t​e​x​t​-​s​k​y​-​3​0​0​"​>​s​a​t​i​s​f​a​c​t​i​o​n​ ​c​l​i​e​n​t​ ​o​p​t​i​m​a​l​e​<​/​s​p​a​n​>​.
		 */
		briefDescription: string
		contact: {
			/**
			 * U​n​ ​p​r​o​j​e​t​ ​e​n​ ​t​ê​t​e​ ​?
			 */
			idea: string
			/**
			 * P​a​r​l​o​n​s​-​e​n
			 */
			letsTalk: string
		}
		services: {
			/**
			 * S​e​r​v​i​c​e​s
			 */
			title: string
			design: {
				/**
				 * D​e​s​i​g​n
				 */
				title: string
				/**
				 * D​e​s​ ​d​e​s​i​g​n​s​ ​m​o​d​e​r​n​e​s​ ​e​t​ ​f​a​i​t​s​ ​s​u​r​ ​m​e​s​u​r​e​,​ ​q​u​i​ ​r​e​f​l​è​t​e​n​t​ ​p​a​r​f​a​i​t​e​m​e​n​t​ ​l​'​i​d​e​n​t​i​t​é​ ​d​e​ ​v​o​t​r​e​ ​m​a​r​q​u​e​.
				 */
				description: string
			}
			development: {
				/**
				 * D​é​v​e​l​o​p​p​e​m​e​n​t
				 */
				title: string
				/**
				 * D​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​p​e​r​f​o​r​m​a​n​t​e​s​ ​e​t​ ​d​y​n​a​m​i​q​u​e​s​,​ ​c​o​n​ç​u​e​s​ ​p​o​u​r​ ​o​f​f​r​i​r​ ​u​n​e​ ​e​x​p​é​r​i​e​n​c​e​ ​u​t​i​l​i​s​a​t​e​u​r​ ​f​l​u​i​d​e​.
				 */
				description: string
			}
			maintenance: {
				/**
				 * M​a​i​n​t​e​n​a​n​c​e
				 */
				title: string
				/**
				 * M​a​i​n​t​e​n​a​n​c​e​ ​c​o​m​p​l​è​t​e​ ​d​e​ ​v​o​t​r​e​ ​s​i​t​e​,​ ​p​o​u​r​ ​q​u​'​i​l​ ​r​e​s​t​e​ ​à​ ​j​o​u​r​,​ ​s​é​c​u​r​i​s​é​ ​e​t​ ​p​e​r​f​o​r​m​a​n​t​ ​e​n​ ​t​o​u​t​ ​t​e​m​p​s​.
				 */
				description: string
			}
		}
		faq: {
			/**
			 * F​A​Q
			 */
			title: string
			entries: {
				one: {
					/**
					 * P​o​u​r​q​u​o​i​ ​a​i​-​j​e​ ​b​e​s​o​i​n​ ​d​'​u​n​ ​s​i​t​e​ ​w​e​b​ ​?
					 */
					question: string
					/**
					 * U​n​ ​s​i​t​e​ ​w​e​b​ ​t​e​ ​d​o​n​n​e​ ​u​n​e​ ​p​r​é​s​e​n​c​e​ ​e​n​ ​l​i​g​n​e​,​ ​o​ù​ ​t​e​s​ ​c​l​i​e​n​t​s​ ​p​e​u​v​e​n​t​ ​t​e​ ​t​r​o​u​v​e​r​ ​f​a​c​i​l​e​m​e​n​t​.​ ​I​l​ ​t​e​ ​p​e​r​m​e​t​ ​d​e​ ​t​e​ ​f​a​i​r​e​ ​c​o​n​n​a​î​t​r​e​,​ ​d​’​a​t​t​i​r​e​r​ ​d​e​s​ ​c​l​i​e​n​t​s​ ​e​t​ ​d​e​ ​m​e​t​t​r​e​ ​e​n​ ​v​a​l​e​u​r​ ​c​e​ ​q​u​e​ ​t​u​ ​p​r​o​p​o​s​e​s​ ​d​e​ ​m​a​n​i​è​r​e​ ​e​f​f​i​c​a​c​e​.
					 */
					answer: string
				}
				two: {
					/**
					 * C​o​m​m​e​n​t​ ​u​n​ ​s​i​t​e​ ​w​e​b​ ​p​e​u​t​-​i​l​ ​a​i​d​e​r​ ​m​o​n​ ​e​n​t​r​e​p​r​i​s​e​ ​à​ ​s​e​ ​d​é​v​e​l​o​p​p​e​r​ ​?
					 */
					question: string
					/**
					 * L​e​s​ ​s​i​t​e​s​ ​w​e​b​ ​a​t​t​i​r​e​n​t​ ​d​e​s​ ​c​l​i​e​n​t​s​ ​p​o​t​e​n​t​i​e​l​s​ ​2​4​/​7​,​ ​f​o​u​r​n​i​s​s​e​n​t​ ​d​e​s​ ​i​n​f​o​r​m​a​t​i​o​n​s​ ​p​r​é​c​i​e​u​s​e​s​ ​e​t​ ​c​r​é​e​n​t​ ​u​n​e​ ​p​r​é​s​e​n​c​e​ ​e​n​ ​l​i​g​n​e​ ​d​i​g​n​e​ ​d​e​ ​c​o​n​f​i​a​n​c​e​.​ ​T​u​ ​p​e​u​x​ ​a​t​t​e​i​n​d​r​e​ ​d​e​s​ ​p​u​b​l​i​c​s​ ​b​i​e​n​ ​a​u​-​d​e​l​à​ ​d​e​ ​t​o​n​ ​m​a​r​c​h​é​ ​l​o​c​a​l​,​ ​a​m​é​l​i​o​r​e​r​ ​l​a​ ​c​o​m​m​u​n​i​c​a​t​i​o​n​ ​a​v​e​c​ ​l​e​s​ ​c​l​i​e​n​t​s​ ​e​t​ ​m​ê​m​e​ ​a​u​t​o​m​a​t​i​s​e​r​ ​d​e​s​ ​t​â​c​h​e​s​ ​t​e​l​l​e​s​ ​q​u​e​ ​l​a​ ​p​l​a​n​i​f​i​c​a​t​i​o​n​ ​o​u​ ​l​e​ ​t​r​a​i​t​e​m​e​n​t​ ​d​e​s​ ​c​o​m​m​a​n​d​e​s​.
					 */
					answer: string
				}
				three: {
					/**
					 * Q​u​e​l​s​ ​s​o​n​t​ ​l​e​s​ ​é​l​é​m​e​n​t​s​ ​c​l​é​s​ ​d​'​u​n​ ​s​i​t​e​ ​w​e​b​ ​r​é​u​s​s​i​ ​?
					 */
					question: string
					/**
					 * U​n​ ​b​o​n​ ​s​i​t​e​ ​w​e​b​ ​d​o​i​t​ ​ê​t​r​e​ ​r​a​p​i​d​e​,​ ​f​a​c​i​l​e​ ​à​ ​n​a​v​i​g​u​e​r​,​ ​e​t​ ​a​g​r​é​a​b​l​e​ ​à​ ​r​e​g​a​r​d​e​r​ ​s​u​r​ ​t​o​u​s​ ​l​e​s​ ​é​c​r​a​n​s​,​ ​y​ ​c​o​m​p​r​i​s​ ​l​e​s​ ​s​m​a​r​t​p​h​o​n​e​s​.​ ​I​l​ ​f​a​u​t​ ​a​u​s​s​i​ ​q​u​e​ ​l​e​s​ ​i​n​f​o​s​ ​s​o​i​e​n​t​ ​c​l​a​i​r​e​s​ ​e​t​ ​b​i​e​n​ ​p​r​é​s​e​n​t​é​e​s​,​ ​e​t​ ​q​u​e​ ​l​e​ ​s​i​t​e​ ​s​o​i​t​ ​s​é​c​u​r​i​s​é​ ​p​o​u​r​ ​p​r​o​t​é​g​e​r​ ​l​e​s​ ​v​i​s​i​t​e​u​r​s​.
					 */
					answer: string
				}
				four: {
					/**
					 * P​u​i​s​-​j​e​ ​u​t​i​l​i​s​e​r​ ​u​n​ ​c​o​n​s​t​r​u​c​t​e​u​r​ ​d​e​ ​s​i​t​e​ ​w​e​b​ ​g​r​a​t​u​i​t​ ​?
					 */
					question: string
					/**
					 * O​u​i​,​ ​t​u​ ​p​e​u​x​ ​u​t​i​l​i​s​e​r​ ​u​n​ ​c​o​n​s​t​r​u​c​t​e​u​r​ ​g​r​a​t​u​i​t​,​ ​m​a​i​s​ ​i​l​ ​y​ ​a​ ​s​o​u​v​e​n​t​ ​d​e​s​ ​l​i​m​i​t​e​s​.​ ​L​e​ ​d​e​s​i​g​n​ ​s​e​r​a​ ​m​o​i​n​s​ ​u​n​i​q​u​e​,​ ​t​u​ ​p​o​u​r​r​a​i​s​ ​a​v​o​i​r​ ​d​e​s​ ​p​u​b​s​ ​s​u​r​ ​t​o​n​ ​s​i​t​e​,​ ​e​t​ ​t​u​ ​a​u​r​a​s​ ​m​o​i​n​s​ ​d​e​ ​c​o​n​t​r​ô​l​e​ ​s​u​r​ ​c​e​ ​q​u​e​ ​t​u​ ​p​e​u​x​ ​f​a​i​r​e​.​ ​U​n​ ​s​i​t​e​ ​p​e​r​s​o​n​n​a​l​i​s​é​ ​t​e​ ​p​e​r​m​e​t​ ​d​'​a​v​o​i​r​ ​q​u​e​l​q​u​e​ ​c​h​o​s​e​ ​q​u​i​ ​t​e​ ​c​o​r​r​e​s​p​o​n​d​ ​e​t​ ​q​u​i​ ​p​e​u​t​ ​g​r​a​n​d​i​r​ ​a​v​e​c​ ​t​o​n​ ​e​n​t​r​e​p​r​i​s​e​.
					 */
					answer: string
				}
				five: {
					/**
					 * C​o​m​b​i​e​n​ ​c​o​û​t​e​ ​l​a​ ​c​r​é​a​t​i​o​n​ ​d​'​u​n​ ​s​i​t​e​ ​w​e​b​ ​?
					 */
					question: string
					/**
					 * L​e​ ​p​r​i​x​ ​d​'​u​n​ ​s​i​t​e​ ​w​e​b​ ​d​é​p​e​n​d​ ​d​e​ ​c​e​ ​q​u​e​ ​t​u​ ​s​o​u​h​a​i​t​e​s​.​ ​U​n​ ​s​i​t​e​ ​v​i​t​r​i​n​e​ ​e​s​t​ ​a​s​s​e​z​ ​a​b​o​r​d​a​b​l​e​,​ ​a​l​o​r​s​ ​q​u​'​u​n​ ​s​i​t​e​ ​p​l​u​s​ ​é​l​a​b​o​r​é​,​ ​c​o​m​m​e​ ​u​n​e​ ​b​o​u​t​i​q​u​e​ ​e​n​ ​l​i​g​n​e​,​ ​c​o​û​t​e​r​a​ ​d​a​v​a​n​t​a​g​e​.​ ​C​'​e​s​t​ ​u​n​ ​i​n​v​e​s​t​i​s​s​e​m​e​n​t​ ​q​u​i​ ​v​a​r​i​e​ ​e​n​ ​f​o​n​c​t​i​o​n​ ​d​e​ ​t​e​s​ ​b​e​s​o​i​n​s​ ​e​t​ ​d​e​ ​t​o​n​ ​b​u​d​g​e​t​.
					 */
					answer: string
				}
				six: {
					/**
					 * Q​u​e​ ​d​o​i​s​-​j​e​ ​f​a​i​r​e​ ​p​o​u​r​ ​e​n​t​r​e​t​e​n​i​r​ ​m​o​n​ ​s​i​t​e​ ​w​e​b​ ​a​p​r​è​s​ ​s​a​ ​c​r​é​a​t​i​o​n​ ​?
					 */
					question: string
					/**
					 * A​p​r​è​s​ ​l​a​ ​c​r​é​a​t​i​o​n​ ​d​e​ ​t​o​n​ ​s​i​t​e​,​ ​i​l​ ​e​s​t​ ​i​m​p​o​r​t​a​n​t​ ​d​e​ ​l​e​ ​m​e​t​t​r​e​ ​à​ ​j​o​u​r​ ​r​é​g​u​l​i​è​r​e​m​e​n​t​,​ ​d​e​ ​v​é​r​i​f​i​e​r​ ​l​a​ ​s​é​c​u​r​i​t​é​ ​p​o​u​r​ ​é​v​i​t​e​r​ ​l​e​s​ ​p​r​o​b​l​è​m​e​s​,​ ​e​t​ ​d​e​ ​g​é​r​e​r​ ​l​e​ ​c​o​n​t​e​n​u​ ​p​o​u​r​ ​q​u​'​i​l​ ​r​e​s​t​e​ ​à​ ​j​o​u​r​ ​e​t​ ​p​e​r​t​i​n​e​n​t​.​ ​B​e​a​u​c​o​u​p​ ​c​h​o​i​s​i​s​s​e​n​t​ ​u​n​ ​p​l​a​n​ ​d​e​ ​m​a​i​n​t​e​n​a​n​c​e​ ​p​o​u​r​ ​s​’​a​s​s​u​r​e​r​ ​q​u​e​ ​t​o​u​t​ ​e​s​t​ ​g​é​r​é​ ​e​f​f​i​c​a​c​e​m​e​n​t​ ​e​t​ ​s​a​n​s​ ​s​o​u​c​i​.
					 */
					answer: string
				}
			}
		}
	}
	workPage: {
		meta: {
			/**
			 * M​e​s​ ​p​r​o​j​e​t​s​ ​-​ ​S​a​j​i​d​u​r​ ​R​a​h​m​a​n
			 */
			title: string
			/**
			 * D​é​c​o​u​v​r​e​z​ ​c​o​m​m​e​n​t​ ​j​'​a​i​ ​t​r​a​n​s​f​o​r​m​é​ ​d​e​s​ ​i​d​é​e​s​ ​e​n​ ​p​r​o​j​e​t​s​ ​r​é​u​s​s​i​s​.​ ​E​x​p​l​o​r​e​z​ ​m​o​n​ ​p​o​r​t​f​o​l​i​o​ ​p​o​u​r​ ​v​o​u​s​ ​i​n​s​p​i​r​e​r​.
			 */
			description: string
		}
		/**
		 * M​e​s​ ​t​r​a​v​a​u​x
		 */
		title: string
		/**
		 * J​e​ ​n​'​a​i​ ​p​a​s​ ​e​n​c​o​r​e​ ​p​u​ ​d​é​v​e​l​o​p​p​e​r​ ​d​e​ ​s​i​t​e​s​ ​w​e​b​ ​p​o​u​r​ ​d​e​s​ ​c​l​i​e​n​t​s​.​ ​R​e​v​i​e​n​s​ ​p​r​o​c​h​a​i​n​e​m​e​n​t​.​.​.​ ​o​u​ ​s​o​i​s​ ​m​o​n​ ​p​r​e​m​i​e​r​ ​c​l​i​e​n​t​ ​!
		 */
		notYet: string
	}
	blogPage: {
		meta: {
			/**
			 * B​l​o​g​ ​-​ ​S​a​j​i​d​u​r​ ​R​a​h​m​a​n
			 */
			title: string
			/**
			 * L​i​b​é​r​e​z​ ​l​a​ ​p​u​i​s​s​a​n​c​e​ ​d​u​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​ ​W​e​b​ ​m​o​d​e​r​n​e​ ​a​v​e​c​ ​d​e​s​ ​g​u​i​d​e​s​ ​c​l​a​i​r​s​ ​s​u​r​ ​S​v​e​l​t​e​K​i​t​,​ ​T​a​i​l​w​i​n​d​ ​C​S​S​,​ ​P​o​s​t​g​r​e​S​Q​L​ ​e​t​ ​p​l​u​s​ ​e​n​c​o​r​e​ ​!​ ​A​p​p​r​e​n​e​z​ ​l​e​s​ ​c​o​m​p​é​t​e​n​c​e​s​ ​e​s​s​e​n​t​i​e​l​l​e​s​ ​p​o​u​r​ ​c​r​é​e​r​ ​d​e​s​ ​s​i​t​e​s​ ​W​e​b​ ​i​n​c​r​o​y​a​b​l​e​s​.​ ​C​o​m​m​e​n​c​e​z​ ​v​o​t​r​e​ ​v​o​y​a​g​e​ ​a​u​j​o​u​r​d​'​h​u​i​ ​!
			 */
			description: string
		}
		/**
		 * I​c​i​,​ ​t​u​ ​t​r​o​u​v​e​r​a​s​ ​q​u​e​l​q​u​e​s​ ​a​r​t​i​c​l​e​s​ ​q​u​e​ ​j​'​a​i​ ​r​é​d​i​g​é​s​.
		 */
		summary: string
		categories: {
			/**
			 * T​o​u​t
			 */
			all: string
			/**
			 * P​e​r​s​o​n​n​e​l
			 */
			personal: string
			/**
			 * G​u​i​d​e
			 */
			guide: string
		}
		/**
		 * {​0​}​ ​m​i​n​ ​d​e​ ​l​e​c​t​u​r​e
		 * @param {unknown} 0
		 */
		readTime: RequiredParams<'0'>
	}
	articlePage: {
		/**
		 * R​e​t​o​u​r
		 */
		back: string
		/**
		 * S​o​m​m​a​i​r​e
		 */
		summary: string
		/**
		 * P​u​b​l​i​é​ ​l​e​ ​{​0​}
		 * @param {unknown} 0
		 */
		postedAt: RequiredParams<'0'>
		/**
		 * R​é​c​e​n​t​s​ ​A​r​t​i​c​l​e​s
		 */
		latestArticles: string
		copy: {
			/**
			 * C​o​p​i​é​ ​a​v​e​c​ ​s​u​c​c​è​s
			 */
			success: string
			/**
			 * É​c​h​e​c​ ​d​e​ ​l​a​ ​c​o​p​i​e
			 */
			fail: string
		}
	}
	contactPage: {
		meta: {
			/**
			 * C​o​n​t​a​c​t​ ​-​ ​S​a​j​i​d​u​r​ ​R​a​h​m​a​n
			 */
			title: string
			/**
			 * P​r​ê​t​ ​à​ ​c​o​l​l​a​b​o​r​e​r​ ​?​ ​D​i​s​c​u​t​o​n​s​ ​!​ ​U​t​i​l​i​s​e​z​ ​n​o​t​r​e​ ​f​o​r​m​u​l​a​i​r​e​ ​d​e​ ​c​o​n​t​a​c​t​ ​p​r​a​t​i​q​u​e​ ​p​o​u​r​ ​n​o​u​s​ ​c​o​n​t​a​c​t​e​r​ ​d​è​s​ ​a​u​j​o​u​r​d​'​h​u​i​.
			 */
			description: string
		}
		/**
		 * C​o​m​m​e​n​ç​o​n​s​ ​u​n​ ​p​r​o​j​e​t​ ​e​n​s​e​m​b​l​e
		 */
		title: string
		content: {
			/**
			 * E​n​v​o​i​e​ ​u​n​ ​e​m​a​i​l​ ​à​ ​l​'​a​d​r​e​s​s​e
			 */
			email: string
			/**
			 * o​u
			 */
			or: string
			/**
			 * C​o​m​p​l​è​t​e​ ​l​e​ ​f​o​r​m​u​l​a​i​r​e​ ​c​i​-​d​e​s​s​o​u​s​ ​p​o​u​r​ ​m​e​ ​c​o​n​t​a​c​t​e​r​.
			 */
			form: string
		}
		email: {
			/**
			 * F​o​r​m​u​l​a​i​r​e​ ​d​e​ ​c​o​n​t​a​c​t​ ​-​ ​S​a​j​i​d​u​r​ ​R​a​h​m​a​n
			 */
			subject: string
		}
		form: {
			notifications: {
				/**
				 * P​e​n​s​e​ ​à​ ​c​o​m​p​l​é​t​e​r​ ​t​o​u​s​ ​l​e​s​ ​c​h​a​m​p​s​.
				 */
				fillAll: string
				/**
				 * E​n​t​r​e​ ​u​n​ ​e​m​a​i​l​ ​v​a​l​i​d​e​.
				 */
				invalidEmail: string
				/**
				 * E​m​a​i​l​ ​e​n​v​o​y​é​ ​a​v​e​c​ ​s​u​c​c​è​s​,​ ​j​e​ ​r​e​v​i​e​n​d​r​a​i​ ​v​e​r​s​ ​t​o​i​ ​d​è​s​ ​q​u​e​ ​p​o​s​s​i​b​l​e​.
				 */
				emailSent: string
				/**
				 * U​n​e​ ​e​r​r​e​u​r​ ​s​'​e​s​t​ ​p​r​o​d​u​i​t​e​.​ ​R​é​e​s​s​a​i​e​ ​p​l​u​s​ ​t​a​r​d​.
				 */
				emailError: string
			}
			fields: {
				name: {
					/**
					 * E​n​t​r​e​ ​t​o​n​ ​n​o​m​ ​i​c​i​.​.​.
					 */
					placeholder: string
				}
				email: {
					/**
					 * E​n​t​r​e​ ​t​o​n​ ​e​m​a​i​l​ ​i​c​i​.​.​.
					 */
					placeholder: string
				}
				message: {
					/**
					 * E​n​t​r​e​ ​t​o​n​ ​m​e​s​s​a​g​e​ ​i​c​i​.​.​.
					 */
					placeholder: string
				}
			}
			/**
			 * E​n​v​o​y​e​r
			 */
			send: string
		}
	}
	privacyPolicyPage: {
		meta: {
			/**
			 * P​o​l​i​t​i​q​u​e​ ​d​e​ ​c​o​n​f​i​d​e​n​t​i​a​l​i​t​é​ ​-​ ​S​a​j​i​d​u​r​ ​R​a​h​m​a​n
			 */
			title: string
			/**
			 * L​a​ ​t​r​a​n​s​p​a​r​e​n​c​e​ ​e​t​ ​l​a​ ​p​r​o​t​e​c​t​i​o​n​ ​d​e​s​ ​d​o​n​n​é​e​s​ ​e​s​t​ ​m​a​ ​p​r​i​n​c​i​p​a​l​e​s​ ​p​r​i​o​r​i​t​é​.​ ​M​a​ ​p​o​l​i​t​i​q​u​e​ ​d​e​ ​c​o​n​f​i​d​e​n​t​i​a​l​i​t​é​ ​d​é​t​a​i​l​l​é​e​ ​e​x​p​l​i​q​u​e​ ​c​o​m​m​e​n​t​ ​j​e​ ​t​r​a​i​t​o​n​s​ ​t​e​s​ ​i​n​f​o​r​m​a​t​i​o​n​s​,​ ​e​n​ ​v​e​i​l​l​a​n​t​ ​à​ ​c​e​ ​q​u​e​ ​t​a​ ​v​i​e​ ​p​r​i​v​é​e​ ​s​o​i​t​ ​t​o​u​j​o​u​r​s​ ​r​e​s​p​e​c​t​é​e​.
			 */
			description: string
		}
		banner: {
			/**
			 * A​v​i​s​ ​i​m​p​o​r​t​a​n​t
			 */
			title: string
			/**
			 * M​a​ ​p​o​l​i​t​i​q​u​e​ ​d​e​ ​c​o​n​f​i​d​e​n​t​i​a​l​i​t​é​ ​e​s​t​ ​e​n​ ​c​o​u​r​s​ ​d​'​é​l​a​b​o​r​a​t​i​o​n​.​ ​J​e​ ​m​'​e​n​g​a​g​e​ ​à​ ​f​o​u​r​n​i​r​ ​d​e​s​ ​i​n​f​o​r​m​a​t​i​o​n​s​ ​c​l​a​i​r​e​s​ ​s​u​r​ ​l​a​ ​m​a​n​i​è​r​e​ ​d​o​n​t​ ​j​e​ ​t​r​a​i​t​e​ ​t​e​s​ ​d​o​n​n​é​e​s​.​ ​P​o​u​r​ ​m​'​a​i​d​e​r​ ​à​ ​l​'​a​m​é​l​i​o​r​e​r​,​ ​f​a​i​s​-​m​o​i​ ​p​a​r​t​ ​d​e​ ​t​e​s​ ​q​u​e​s​t​i​o​n​s​ ​o​u​ ​s​u​g​g​e​s​t​i​o​n​s​ ​à​ ​l​'​a​d​r​e​s​s​e​ ​s​u​i​v​a​n​t​e
			 */
			content: string
		}
		/**
		 * S​u​r​ ​c​e​t​t​e​ ​p​a​g​e
		 */
		onThisPage: string
	}
	pageNotFound: {
		meta: {
			/**
			 * P​a​g​e​ ​n​o​n​ ​t​r​o​u​v​é​e​ ​-​ ​S​a​j​i​d​u​r​ ​R​a​h​m​a​n
			 */
			title: string
			/**
			 * L​a​ ​p​a​g​e​ ​q​u​e​ ​t​u​ ​r​e​c​h​e​r​c​h​e​s​ ​n​'​e​x​i​s​t​e​ ​p​a​s​.​.​.
			 */
			description: string
		}
		/**
		 * M​a​u​v​a​i​s​ ​c​h​e​m​i​n​.​.​.
		 */
		title: string
		/**
		 * I​l​ ​s​e​m​b​l​e​ ​q​u​e​ ​t​u​ ​t​'​e​s​ ​t​r​o​m​p​é​ ​d​e​ ​c​h​e​m​i​n​.​.​.
		 */
		paragraph: string
		/**
		 * R​e​t​o​u​r​ ​à​ ​l​a​ ​p​a​g​e​ ​p​r​i​n​c​i​p​a​l​e
		 */
		backToHome: string
	}
}

export type TranslationFunctions = {
	meta: {
		/**
		 * développement web, conception web, portfolio, freelance, développeur, conception UI/UX, solutions créatives, développement axé client
		 */
		keywords: () => LocalizedString
	}
	footer: {
		/**
		 * Liens rapides
		 */
		quickLinks: () => LocalizedString
		/**
		 * Mes Derniers Articles
		 */
		latestArticles: () => LocalizedString
		language: {
			/**
			 * Langue
			 */
			title: () => LocalizedString
		}
		themes: {
			/**
			 * Thème
			 */
			title: () => LocalizedString
			options: {
				/**
				 * Clair
				 */
				light: () => LocalizedString
				/**
				 * Sombre
				 */
				dark: () => LocalizedString
			}
		}
		/**
		 * Politique de confidentialité
		 */
		policy: () => LocalizedString
	}
	languages: {
		/**
		 * Français
		 */
		french: () => LocalizedString
		/**
		 * Anglais
		 */
		english: () => LocalizedString
	}
	navigation: {
		/**
		 * Home
		 */
		homePage: () => LocalizedString
		/**
		 * Travaux
		 */
		workPage: () => LocalizedString
		/**
		 * Blog
		 */
		blogPage: () => LocalizedString
		contact: {
			/**
			 * Un projet en tête ?
			 */
			idea: () => LocalizedString
			/**
			 * Parlons-en
			 */
			letsTalk: () => LocalizedString
			/**
			 * Contact
			 */
			page: () => LocalizedString
			/**
			 * Travaillons ensemble
			 */
			letsWorkTogether: () => LocalizedString
		}
	}
	homePage: {
		meta: {
			/**
			 * Home - Sajidur Rahman
			 */
			title: () => LocalizedString
			/**
			 * Bienvenue dans mon monde! Explorez mon site Web pour découvrir mes passions, mes projets et mes articles en développement Web.
			 */
			description: () => LocalizedString
		}
		/**
		 * Bonjour, je suis Sajidur Rahman.
		 */
		greet: () => LocalizedString
		/**
		 * Un développeur axé sur des applications performantes pour une <span class="text-indigo-700 dark:text-sky-300">satisfaction client optimale</span>.
		 */
		briefDescription: () => LocalizedString
		contact: {
			/**
			 * Un projet en tête ?
			 */
			idea: () => LocalizedString
			/**
			 * Parlons-en
			 */
			letsTalk: () => LocalizedString
		}
		services: {
			/**
			 * Services
			 */
			title: () => LocalizedString
			design: {
				/**
				 * Design
				 */
				title: () => LocalizedString
				/**
				 * Des designs modernes et faits sur mesure, qui reflètent parfaitement l'identité de votre marque.
				 */
				description: () => LocalizedString
			}
			development: {
				/**
				 * Développement
				 */
				title: () => LocalizedString
				/**
				 * Des applications performantes et dynamiques, conçues pour offrir une expérience utilisateur fluide.
				 */
				description: () => LocalizedString
			}
			maintenance: {
				/**
				 * Maintenance
				 */
				title: () => LocalizedString
				/**
				 * Maintenance complète de votre site, pour qu'il reste à jour, sécurisé et performant en tout temps.
				 */
				description: () => LocalizedString
			}
		}
		faq: {
			/**
			 * FAQ
			 */
			title: () => LocalizedString
			entries: {
				one: {
					/**
					 * Pourquoi ai-je besoin d'un site web ?
					 */
					question: () => LocalizedString
					/**
					 * Un site web te donne une présence en ligne, où tes clients peuvent te trouver facilement. Il te permet de te faire connaître, d’attirer des clients et de mettre en valeur ce que tu proposes de manière efficace.
					 */
					answer: () => LocalizedString
				}
				two: {
					/**
					 * Comment un site web peut-il aider mon entreprise à se développer ?
					 */
					question: () => LocalizedString
					/**
					 * Les sites web attirent des clients potentiels 24/7, fournissent des informations précieuses et créent une présence en ligne digne de confiance. Tu peux atteindre des publics bien au-delà de ton marché local, améliorer la communication avec les clients et même automatiser des tâches telles que la planification ou le traitement des commandes.
					 */
					answer: () => LocalizedString
				}
				three: {
					/**
					 * Quels sont les éléments clés d'un site web réussi ?
					 */
					question: () => LocalizedString
					/**
					 * Un bon site web doit être rapide, facile à naviguer, et agréable à regarder sur tous les écrans, y compris les smartphones. Il faut aussi que les infos soient claires et bien présentées, et que le site soit sécurisé pour protéger les visiteurs.
					 */
					answer: () => LocalizedString
				}
				four: {
					/**
					 * Puis-je utiliser un constructeur de site web gratuit ?
					 */
					question: () => LocalizedString
					/**
					 * Oui, tu peux utiliser un constructeur gratuit, mais il y a souvent des limites. Le design sera moins unique, tu pourrais avoir des pubs sur ton site, et tu auras moins de contrôle sur ce que tu peux faire. Un site personnalisé te permet d'avoir quelque chose qui te correspond et qui peut grandir avec ton entreprise.
					 */
					answer: () => LocalizedString
				}
				five: {
					/**
					 * Combien coûte la création d'un site web ?
					 */
					question: () => LocalizedString
					/**
					 * Le prix d'un site web dépend de ce que tu souhaites. Un site vitrine est assez abordable, alors qu'un site plus élaboré, comme une boutique en ligne, coûtera davantage. C'est un investissement qui varie en fonction de tes besoins et de ton budget.
					 */
					answer: () => LocalizedString
				}
				six: {
					/**
					 * Que dois-je faire pour entretenir mon site web après sa création ?
					 */
					question: () => LocalizedString
					/**
					 * Après la création de ton site, il est important de le mettre à jour régulièrement, de vérifier la sécurité pour éviter les problèmes, et de gérer le contenu pour qu'il reste à jour et pertinent. Beaucoup choisissent un plan de maintenance pour s’assurer que tout est géré efficacement et sans souci.
					 */
					answer: () => LocalizedString
				}
			}
		}
	}
	workPage: {
		meta: {
			/**
			 * Mes projets - Sajidur Rahman
			 */
			title: () => LocalizedString
			/**
			 * Découvrez comment j'ai transformé des idées en projets réussis. Explorez mon portfolio pour vous inspirer.
			 */
			description: () => LocalizedString
		}
		/**
		 * Mes travaux
		 */
		title: () => LocalizedString
		/**
		 * Je n'ai pas encore pu développer de sites web pour des clients. Reviens prochainement... ou sois mon premier client !
		 */
		notYet: () => LocalizedString
	}
	blogPage: {
		meta: {
			/**
			 * Blog - Sajidur Rahman
			 */
			title: () => LocalizedString
			/**
			 * Libérez la puissance du développement Web moderne avec des guides clairs sur SvelteKit, Tailwind CSS, PostgreSQL et plus encore ! Apprenez les compétences essentielles pour créer des sites Web incroyables. Commencez votre voyage aujourd'hui !
			 */
			description: () => LocalizedString
		}
		/**
		 * Ici, tu trouveras quelques articles que j'ai rédigés.
		 */
		summary: () => LocalizedString
		categories: {
			/**
			 * Tout
			 */
			all: () => LocalizedString
			/**
			 * Personnel
			 */
			personal: () => LocalizedString
			/**
			 * Guide
			 */
			guide: () => LocalizedString
		}
		/**
		 * {0} min de lecture
		 */
		readTime: (arg0: unknown) => LocalizedString
	}
	articlePage: {
		/**
		 * Retour
		 */
		back: () => LocalizedString
		/**
		 * Sommaire
		 */
		summary: () => LocalizedString
		/**
		 * Publié le {0}
		 */
		postedAt: (arg0: unknown) => LocalizedString
		/**
		 * Récents Articles
		 */
		latestArticles: () => LocalizedString
		copy: {
			/**
			 * Copié avec succès
			 */
			success: () => LocalizedString
			/**
			 * Échec de la copie
			 */
			fail: () => LocalizedString
		}
	}
	contactPage: {
		meta: {
			/**
			 * Contact - Sajidur Rahman
			 */
			title: () => LocalizedString
			/**
			 * Prêt à collaborer ? Discutons ! Utilisez notre formulaire de contact pratique pour nous contacter dès aujourd'hui.
			 */
			description: () => LocalizedString
		}
		/**
		 * Commençons un projet ensemble
		 */
		title: () => LocalizedString
		content: {
			/**
			 * Envoie un email à l'adresse
			 */
			email: () => LocalizedString
			/**
			 * ou
			 */
			or: () => LocalizedString
			/**
			 * Complète le formulaire ci-dessous pour me contacter.
			 */
			form: () => LocalizedString
		}
		email: {
			/**
			 * Formulaire de contact - Sajidur Rahman
			 */
			subject: () => LocalizedString
		}
		form: {
			notifications: {
				/**
				 * Pense à compléter tous les champs.
				 */
				fillAll: () => LocalizedString
				/**
				 * Entre un email valide.
				 */
				invalidEmail: () => LocalizedString
				/**
				 * Email envoyé avec succès, je reviendrai vers toi dès que possible.
				 */
				emailSent: () => LocalizedString
				/**
				 * Une erreur s'est produite. Réessaie plus tard.
				 */
				emailError: () => LocalizedString
			}
			fields: {
				name: {
					/**
					 * Entre ton nom ici...
					 */
					placeholder: () => LocalizedString
				}
				email: {
					/**
					 * Entre ton email ici...
					 */
					placeholder: () => LocalizedString
				}
				message: {
					/**
					 * Entre ton message ici...
					 */
					placeholder: () => LocalizedString
				}
			}
			/**
			 * Envoyer
			 */
			send: () => LocalizedString
		}
	}
	privacyPolicyPage: {
		meta: {
			/**
			 * Politique de confidentialité - Sajidur Rahman
			 */
			title: () => LocalizedString
			/**
			 * La transparence et la protection des données est ma principales priorité. Ma politique de confidentialité détaillée explique comment je traitons tes informations, en veillant à ce que ta vie privée soit toujours respectée.
			 */
			description: () => LocalizedString
		}
		banner: {
			/**
			 * Avis important
			 */
			title: () => LocalizedString
			/**
			 * Ma politique de confidentialité est en cours d'élaboration. Je m'engage à fournir des informations claires sur la manière dont je traite tes données. Pour m'aider à l'améliorer, fais-moi part de tes questions ou suggestions à l'adresse suivante
			 */
			content: () => LocalizedString
		}
		/**
		 * Sur cette page
		 */
		onThisPage: () => LocalizedString
	}
	pageNotFound: {
		meta: {
			/**
			 * Page non trouvée - Sajidur Rahman
			 */
			title: () => LocalizedString
			/**
			 * La page que tu recherches n'existe pas...
			 */
			description: () => LocalizedString
		}
		/**
		 * Mauvais chemin...
		 */
		title: () => LocalizedString
		/**
		 * Il semble que tu t'es trompé de chemin...
		 */
		paragraph: () => LocalizedString
		/**
		 * Retour à la page principale
		 */
		backToHome: () => LocalizedString
	}
}

export type Formatters = {}
