// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	footer: {
		/**
		 * L​i​e​n​s​ ​r​a​p​i​d​e​s
		 */
		quickLinks: string
		/**
		 * M​e​s​ ​D​e​r​n​i​e​r​s​ ​A​r​t​i​c​l​e​s
		 */
		latestArticles: string
		language: {
			/**
			 * L​a​n​g​u​e
			 */
			title: string
		}
	}
	languages: {
		/**
		 * F​r​a​n​ç​a​i​s
		 */
		french: string
		/**
		 * A​n​g​l​a​i​s
		 */
		english: string
	}
	navigation: {
		/**
		 * H​o​m​e
		 */
		homePage: string
		/**
		 * M​e​s​ ​t​r​a​v​a​u​x
		 */
		workPage: string
		/**
		 * M​o​n​ ​b​l​o​g
		 */
		blogPage: string
		contact: {
			/**
			 * U​n​ ​p​r​o​j​e​t​ ​e​n​ ​t​ê​t​e​ ​?
			 */
			idea: string
			/**
			 * P​a​r​l​o​n​s​-​e​n
			 */
			letsTalk: string
			/**
			 * C​o​n​t​a​c​t
			 */
			page: string
			/**
			 * T​r​a​v​a​i​l​l​o​n​s​ ​e​n​s​e​m​b​l​e
			 */
			letsWorkTogether: string
		}
	}
	homePage: {
		/**
		 * B​o​n​j​o​u​r​,​ ​j​e​ ​s​u​i​s​ ​S​a​j​i​d​u​r​ ​R​a​h​m​a​n​.
		 */
		greet: string
		/**
		 * U​n​ ​d​é​v​e​l​o​p​p​e​u​r​ ​w​e​b​ ​a​x​é​ ​s​u​r​ ​l​e​s​ ​i​n​t​e​r​f​a​c​e​s​ ​u​t​i​l​i​s​a​t​e​u​r​ ​p​o​u​r​ ​u​n​ ​d​e​s​i​g​n​ ​f​l​u​i​d​e​ ​e​t​ ​u​n​e​ ​s​a​t​i​s​f​a​c​t​i​o​n​ ​c​l​i​e​n​t​ ​o​p​t​i​m​a​l​e​.
		 */
		briefDescription: string
		keywords: {
			/**
			 * D​e​s​i​g​n
			 */
			design: string
			/**
			 * D​é​v​e​l​o​p​p​e​m​e​n​t
			 */
			development: string
			/**
			 * M​a​i​n​t​e​n​a​n​c​e
			 */
			maintenance: string
		}
		contact: {
			/**
			 * U​n​ ​p​r​o​j​e​t​ ​e​n​ ​t​ê​t​e​ ​?
			 */
			idea: string
			/**
			 * P​a​r​l​o​n​s​-​e​n
			 */
			letsTalk: string
		}
		services: {
			/**
			 * S​e​r​v​i​c​e​s
			 */
			title: string
			benefits: {
				/**
				 * P​r​e​s​t​a​t​i​o​n​s​ ​&​ ​S​e​r​v​i​c​e​s
				 */
				title: string
				/**
				 * D​e​s​i​g​n​ ​w​e​b​,​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​ ​w​e​b​,​ ​S​E​O​,​ ​s​u​i​v​i​ ​r​é​g​u​l​i​e​r​,​ ​s​i​t​e​s​ ​w​e​b​ ​r​e​s​p​o​n​s​i​v​e​s​.
				 */
				description: string
			}
			performance: {
				/**
				 * O​p​t​i​m​i​s​é​ ​&​ ​P​e​r​f​o​r​m​a​n​t
				 */
				title: string
				/**
				 * C​r​é​a​t​i​o​n​ ​d​e​ ​s​i​t​e​s​ ​w​e​b​ ​p​e​r​f​o​r​m​a​n​t​s​ ​e​t​ ​o​p​t​i​m​i​s​é​s​ ​p​o​u​r​ ​l​e​ ​r​é​f​é​r​e​n​c​e​m​e​n​t​.
				 */
				description: string
			}
			collaboration: {
				/**
				 * C​o​l​l​a​b​o​r​a​t​i​o​n​ ​&​ ​É​v​o​l​u​t​i​o​n
				 */
				title: string
				/**
				 * C​o​l​l​a​b​o​r​a​t​i​o​n​ ​e​n​ ​c​o​n​t​i​n​u​ ​p​o​u​r​ ​r​é​p​o​n​d​r​e​ ​à​ ​d​e​s​ ​b​e​s​o​i​n​s​ ​q​u​i​ ​é​v​o​l​u​e​n​t​.
				 */
				description: string
			}
			accessibility: {
				/**
				 * A​c​c​e​s​s​i​b​i​l​i​t​é​ ​&​ ​U​X
				 */
				title: string
				/**
				 * N​a​v​i​g​a​t​i​o​n​ ​i​n​t​u​i​t​i​v​e​,​ ​e​r​g​o​n​o​m​i​e​ ​e​t​ ​c​l​a​r​t​é​.
				 */
				description: string
			}
		}
		aboutMe: {
			/**
			 * À​ ​p​r​o​p​o​s
			 */
			title: string
			/**
			 * P​a​s​s​i​o​n​n​é​ ​p​a​r​ ​l​a​ ​c​r​é​a​t​i​o​n​ ​d​e​ ​s​i​t​e​s​ ​w​e​b​ ​i​n​t​u​i​t​i​f​s​ ​e​t​ ​p​e​r​f​o​r​m​a​n​t​s​,​ ​j​'​é​t​u​d​i​e​ ​a​c​t​u​e​l​l​e​m​e​n​t​ ​à​ ​l​'​E​P​T​M​ ​d​e​ ​S​i​o​n​ ​e​n​ ​t​a​n​t​ ​q​u​e​ ​d​é​v​e​l​o​p​p​e​u​r​ ​d​'​a​p​p​l​i​c​a​t​i​o​n​s​.​ ​J​e​ ​s​o​u​h​a​i​t​e​ ​c​o​n​t​i​n​u​e​r​ ​à​ ​a​p​p​r​e​n​d​r​e​ ​e​t​ ​m​e​ ​p​e​r​f​e​c​t​i​o​n​n​e​r​ ​d​a​n​s​ ​c​e​ ​d​o​m​a​i​n​e​ ​e​n​ ​p​l​e​i​n​e​ ​é​v​o​l​u​t​i​o​n​.
			 */
			studies: string
			skills: {
				/**
				 * M​e​s​ ​c​o​m​p​é​t​e​n​c​e​s​ ​t​e​c​h​n​i​q​u​e​s​ ​i​n​c​l​u​e​n​t
				 */
				title: string
			}
			/**
			 * E​n​ ​d​e​h​o​r​s​ ​d​e​ ​m​e​s​ ​é​t​u​d​e​s​,​ ​j​e​ ​s​u​i​s​ ​p​a​s​s​i​o​n​n​é​ ​p​a​r​ ​l​e​ ​d​e​s​i​g​n​.​ ​J​'​a​i​m​e​ ​é​g​a​l​e​m​e​n​t​ ​l​e​ ​d​e​s​s​i​n​ ​(​a​v​e​c​ ​u​n​e​ ​t​a​b​l​e​t​t​e​ ​g​r​a​p​h​i​q​u​e​)​ ​e​t​ ​l​a​ ​p​o​l​i​t​i​q​u​e​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​e​.
			 */
			hobbies: string
			/**
			 * J​e​ ​s​u​i​s​ ​d​i​s​p​o​n​i​b​l​e​ ​p​o​u​r​ ​d​e​s​ ​m​i​s​s​i​o​n​s​ ​d​e​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​ ​w​e​b​ ​f​r​e​e​l​a​n​c​e​ ​o​u​ ​p​o​u​r​ ​d​e​s​ ​c​o​l​l​a​b​o​r​a​t​i​o​n​s​ ​s​u​r​ ​d​e​s​ ​p​r​o​j​e​t​s​ ​o​p​e​n​-​s​o​u​r​c​e​.
			 */
			availability: string
		}
	}
	workPage: {
		meta: {
			/**
			 * M​e​s​ ​p​r​o​j​e​t​s​ ​-​ ​S​a​j​i​d​u​r​ ​R​a​h​m​a​n
			 */
			title: string
		}
		/**
		 * M​e​s​ ​t​r​a​v​a​u​x
		 */
		title: string
		/**
		 * J​e​ ​n​'​a​i​ ​p​a​s​ ​e​n​c​o​r​e​ ​p​u​ ​d​é​v​e​l​o​p​p​e​r​ ​d​e​ ​s​i​t​e​s​ ​w​e​b​ ​p​o​u​r​ ​d​e​s​ ​c​l​i​e​n​t​s​.​ ​R​e​v​e​n​e​z​ ​p​r​o​c​h​a​i​n​e​m​e​n​t​ ​!
		 */
		notYet: string
	}
	blogPage: {
		meta: {
			/**
			 * B​l​o​g​ ​-​ ​S​a​j​i​d​u​r​ ​R​a​h​m​a​n
			 */
			title: string
		}
		/**
		 * I​c​i​,​ ​v​o​u​s​ ​t​r​o​u​v​e​r​e​z​ ​q​u​e​l​q​u​e​s​ ​a​r​t​i​c​l​e​s​ ​q​u​e​ ​j​'​a​i​ ​r​é​d​i​g​é​s​.​ ​N​é​a​n​m​o​i​n​s​,​ ​i​l​s​ ​n​e​ ​s​o​n​t​ ​d​i​s​p​o​n​i​b​l​e​s​ ​q​u​'​e​n​ ​a​n​g​l​a​i​s​.
		 */
		summary: string
	}
	articlePage: {
		/**
		 * R​e​t​o​u​r
		 */
		back: string
	}
	contactPage: {
		meta: {
			/**
			 * C​o​n​t​a​c​t​ ​-​ ​S​a​j​i​d​u​r​ ​R​a​h​m​a​n
			 */
			title: string
		}
		/**
		 * C​o​m​m​e​n​ç​o​n​s​ ​u​n​ ​p​r​o​j​e​t​ ​e​n​s​e​m​b​l​e
		 */
		letsWorkTogether: string
		/**
		 * C​o​m​p​l​é​t​e​z​ ​l​e​ ​f​o​r​m​u​l​a​i​r​e​ ​c​i​-​d​e​s​s​o​u​s​ ​p​o​u​r​ ​m​e​ ​c​o​n​t​a​c​t​e​r​.
		 */
		completeTheForm: string
		form: {
			notifications: {
				/**
				 * V​e​u​i​l​l​e​z​ ​c​o​m​p​l​é​t​e​r​ ​t​o​u​s​ ​l​e​s​ ​c​h​a​m​p​s​.
				 */
				fillAll: string
				/**
				 * E​n​t​r​e​z​ ​u​n​ ​e​m​a​i​l​ ​v​a​l​i​d​e​.
				 */
				invalidEmail: string
				/**
				 * E​m​a​i​l​ ​e​n​v​o​y​é​ ​a​v​e​c​ ​s​u​c​c​è​s​,​ ​j​e​ ​r​e​v​i​e​n​d​r​a​i​ ​v​e​r​s​ ​v​o​u​s​ ​d​è​s​ ​q​u​e​ ​p​o​s​s​i​b​l​e​.
				 */
				emailSent: string
				/**
				 * U​n​e​ ​e​r​r​e​u​r​ ​s​'​e​s​t​ ​p​r​o​d​u​i​t​e​.​ ​R​é​e​s​s​a​y​e​z​ ​p​l​u​s​ ​t​a​r​d​.
				 */
				emailError: string
			}
			fields: {
				name: {
					/**
					 * E​n​t​r​e​z​ ​v​o​t​r​e​ ​n​o​m​ ​i​c​i​.​.​.
					 */
					placeholder: string
				}
				email: {
					/**
					 * E​n​t​r​e​z​ ​v​o​t​r​e​ ​e​m​a​i​l​ ​i​c​i​.​.​.
					 */
					placeholder: string
				}
				message: {
					/**
					 * E​n​t​r​e​z​ ​v​o​t​r​e​ ​m​e​s​s​a​g​e​ ​i​c​i​.​.​.
					 */
					placeholder: string
				}
			}
			/**
			 * E​n​v​o​y​e​r
			 */
			send: string
		}
	}
}

export type TranslationFunctions = {
	footer: {
		/**
		 * Liens rapides
		 */
		quickLinks: () => LocalizedString
		/**
		 * Mes Derniers Articles
		 */
		latestArticles: () => LocalizedString
		language: {
			/**
			 * Langue
			 */
			title: () => LocalizedString
		}
	}
	languages: {
		/**
		 * Français
		 */
		french: () => LocalizedString
		/**
		 * Anglais
		 */
		english: () => LocalizedString
	}
	navigation: {
		/**
		 * Home
		 */
		homePage: () => LocalizedString
		/**
		 * Mes travaux
		 */
		workPage: () => LocalizedString
		/**
		 * Mon blog
		 */
		blogPage: () => LocalizedString
		contact: {
			/**
			 * Un projet en tête ?
			 */
			idea: () => LocalizedString
			/**
			 * Parlons-en
			 */
			letsTalk: () => LocalizedString
			/**
			 * Contact
			 */
			page: () => LocalizedString
			/**
			 * Travaillons ensemble
			 */
			letsWorkTogether: () => LocalizedString
		}
	}
	homePage: {
		/**
		 * Bonjour, je suis Sajidur Rahman.
		 */
		greet: () => LocalizedString
		/**
		 * Un développeur web axé sur les interfaces utilisateur pour un design fluide et une satisfaction client optimale.
		 */
		briefDescription: () => LocalizedString
		keywords: {
			/**
			 * Design
			 */
			design: () => LocalizedString
			/**
			 * Développement
			 */
			development: () => LocalizedString
			/**
			 * Maintenance
			 */
			maintenance: () => LocalizedString
		}
		contact: {
			/**
			 * Un projet en tête ?
			 */
			idea: () => LocalizedString
			/**
			 * Parlons-en
			 */
			letsTalk: () => LocalizedString
		}
		services: {
			/**
			 * Services
			 */
			title: () => LocalizedString
			benefits: {
				/**
				 * Prestations & Services
				 */
				title: () => LocalizedString
				/**
				 * Design web, développement web, SEO, suivi régulier, sites web responsives.
				 */
				description: () => LocalizedString
			}
			performance: {
				/**
				 * Optimisé & Performant
				 */
				title: () => LocalizedString
				/**
				 * Création de sites web performants et optimisés pour le référencement.
				 */
				description: () => LocalizedString
			}
			collaboration: {
				/**
				 * Collaboration & Évolution
				 */
				title: () => LocalizedString
				/**
				 * Collaboration en continu pour répondre à des besoins qui évoluent.
				 */
				description: () => LocalizedString
			}
			accessibility: {
				/**
				 * Accessibilité & UX
				 */
				title: () => LocalizedString
				/**
				 * Navigation intuitive, ergonomie et clarté.
				 */
				description: () => LocalizedString
			}
		}
		aboutMe: {
			/**
			 * À propos
			 */
			title: () => LocalizedString
			/**
			 * Passionné par la création de sites web intuitifs et performants, j'étudie actuellement à l'EPTM de Sion en tant que développeur d'applications. Je souhaite continuer à apprendre et me perfectionner dans ce domaine en pleine évolution.
			 */
			studies: () => LocalizedString
			skills: {
				/**
				 * Mes compétences techniques incluent
				 */
				title: () => LocalizedString
			}
			/**
			 * En dehors de mes études, je suis passionné par le design. J'aime également le dessin (avec une tablette graphique) et la politique internationale.
			 */
			hobbies: () => LocalizedString
			/**
			 * Je suis disponible pour des missions de développement web freelance ou pour des collaborations sur des projets open-source.
			 */
			availability: () => LocalizedString
		}
	}
	workPage: {
		meta: {
			/**
			 * Mes projets - Sajidur Rahman
			 */
			title: () => LocalizedString
		}
		/**
		 * Mes travaux
		 */
		title: () => LocalizedString
		/**
		 * Je n'ai pas encore pu développer de sites web pour des clients. Revenez prochainement !
		 */
		notYet: () => LocalizedString
	}
	blogPage: {
		meta: {
			/**
			 * Blog - Sajidur Rahman
			 */
			title: () => LocalizedString
		}
		/**
		 * Ici, vous trouverez quelques articles que j'ai rédigés. Néanmoins, ils ne sont disponibles qu'en anglais.
		 */
		summary: () => LocalizedString
	}
	articlePage: {
		/**
		 * Retour
		 */
		back: () => LocalizedString
	}
	contactPage: {
		meta: {
			/**
			 * Contact - Sajidur Rahman
			 */
			title: () => LocalizedString
		}
		/**
		 * Commençons un projet ensemble
		 */
		letsWorkTogether: () => LocalizedString
		/**
		 * Complétez le formulaire ci-dessous pour me contacter.
		 */
		completeTheForm: () => LocalizedString
		form: {
			notifications: {
				/**
				 * Veuillez compléter tous les champs.
				 */
				fillAll: () => LocalizedString
				/**
				 * Entrez un email valide.
				 */
				invalidEmail: () => LocalizedString
				/**
				 * Email envoyé avec succès, je reviendrai vers vous dès que possible.
				 */
				emailSent: () => LocalizedString
				/**
				 * Une erreur s'est produite. Réessayez plus tard.
				 */
				emailError: () => LocalizedString
			}
			fields: {
				name: {
					/**
					 * Entrez votre nom ici...
					 */
					placeholder: () => LocalizedString
				}
				email: {
					/**
					 * Entrez votre email ici...
					 */
					placeholder: () => LocalizedString
				}
				message: {
					/**
					 * Entrez votre message ici...
					 */
					placeholder: () => LocalizedString
				}
			}
			/**
			 * Envoyer
			 */
			send: () => LocalizedString
		}
	}
}

export type Formatters = {}
